In [ ]:
import torch
import numpy as np

In [ ]:
torch_tensor = torch.tensor([1, 2, 3, 4, 5])
print(torch_tensor)

tensor([1, 2, 3, 4, 5])


In [ ]:
print(torch_tensor.dtype)
print(torch_tensor.type())

torch.int64
torch.LongTensor


In [ ]:
torch_tensor = torch.tensor([0.0, 0.1, 0.2, 0.3])
print(torch_tensor)

tensor([0.0000, 0.1000, 0.2000, 0.3000])


In [ ]:
print(torch_tensor.dtype)
print(torch_tensor.type())

torch.float32
torch.FloatTensor


In [ ]:
torch_tensor = torch.tensor([1.0, 2.0, 3.2, 4.3, 5.4, 6.5], dtype = torch.int32)
print(torch_tensor)

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)


In [ ]:
print(torch_tensor.dtype)
print(torch_tensor.type())

torch.int32
torch.IntTensor


In [ ]:
torch_tensor = torch.FloatTensor([0, 1, 2, 3, 4])
print(torch_tensor)

tensor([0., 1., 2., 3., 4.])


In [ ]:
print(torch_tensor.dtype)
print(torch_tensor.type())

torch.float32
torch.FloatTensor


In [ ]:
torch_tensor = torch.FloatTensor([0.1, 1.2, 2.3, 3.4, 4.5, 5.6])
print(torch_tensor)

torch_tensor_0 = torch_tensor.type(torch.IntTensor)
print(torch_tensor_0)

tensor([0.1000, 1.2000, 2.3000, 3.4000, 4.5000, 5.6000])
tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)


In [ ]:
print(torch_tensor.type())
print(torch_tensor_0.type())

torch.FloatTensor
torch.IntTensor


In [ ]:
torch_tensor = torch.tensor([0, 1, 2, 3, 4, 5])
print(torch_tensor)

tensor([0, 1, 2, 3, 4, 5])


In [ ]:
print(torch_tensor.size())
print(torch_tensor.ndimension())

torch.Size([6])
1


In [ ]:
torch_tensor = torch.tensor([1, 2, 3, 4, 5, 6])
print(torch_tensor)

tensor([1, 2, 3, 4, 5, 6])


In [ ]:
torch_tensor = torch_tensor.view(6, 1)
print(torch_tensor)

                              # OR
torch_tensor = torch_tensor.view(-1, 1)
print(torch_tensor)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [ ]:
numpy_array = np.array([1, 2, 3, 4, 5, 6])
print(numpy_array.dtype)

torch_tensor = torch.from_numpy(numpy_array)
print(torch_tensor.dtype)

numpy_array_0 = torch_tensor.numpy()
print(numpy_array_0.dtype)

int64
torch.int64
int64


In [ ]:
torch_tensor = torch.tensor([1, 2, 3, 4, 5])
print(torch_tensor)

tensor([1, 2, 3, 4, 5])


In [ ]:
torch_tensor[0] = 0
print(torch_tensor)

tensor([0, 2, 3, 4, 5])


In [ ]:
torch_tensor_0 = torch_tensor[1:4]
print(torch_tensor_0)

tensor([2, 3, 4])


In [ ]:
torch_tensor_0[0:2] = torch.tensor([0, 1])
print(torch_tensor_0)

tensor([0, 1, 4])


In [ ]:
tensor_u = torch.tensor([1, 0])
tensor_v = torch.tensor([0, 1])

tensor_z = tensor_u + tensor_v
print(tensor_z)

tensor([1, 1])


In [ ]:
tensor_z = tensor_u * tensor_v
print(tensor_z)

tensor([0, 0])


In [ ]:
tensor_z = torch.dot(tensor_u, tensor_v)
print(tensor_z)

tensor(0)


In [ ]:
torch.linspace(-2, 2, steps = 5)

tensor([-2., -1.,  0.,  1.,  2.])

***Derivatives And Partial Derivatives***

In [ ]:
x = torch.tensor(2.0, requires_grad = True)
y = x**2
print(y)
y.backward()
x.grad

tensor(4., grad_fn=<PowBackward0>)


tensor(4.)

In [ ]:
u = torch.tensor(1.0, requires_grad = True)
v = torch.tensor(2.0, requires_grad = True)
f = u*v + u**2
f.backward()
u.grad
v.grad

tensor(1.)