In [1]:
import torch

In [2]:
class LogisticRegression(torch.nn.Module):
  def __init__(self, input_dimension, output_dimension):
    super (LogisticRegression, self).__init__()
    self.input_dimension = input_dimension
    self.output_dimension = output_dimension
    self.layer = torch.nn.Linear(self.input_dimension, self.output_dimension)

  def forward(self, x):
    prediction = torch.sigmoid(self.layer(x))
    return prediction

model = LogisticRegression(input_dimension = 6, output_dimension = 1)

In [3]:
print(model)
for parametres in model.parameters():
  print(parametres)

LogisticRegression(
  (layer): Linear(in_features=6, out_features=1, bias=True)
)
Parameter containing:
tensor([[-0.1257, -0.3965,  0.1026, -0.3230,  0.1686, -0.1294]],
       requires_grad=True)
Parameter containing:
tensor([-0.3254], requires_grad=True)


***lazy method which is not recommended to save and load pytorch models.***

In [4]:
file = 'model.pth'
torch.save(model, file)

In [5]:
load_saved_model = torch.load(file)
load_saved_model.eval()

print(load_saved_model)
for parametres in load_saved_model.parameters():
  print(parametres)

LogisticRegression(
  (layer): Linear(in_features=6, out_features=1, bias=True)
)
Parameter containing:
tensor([[-0.1257, -0.3965,  0.1026, -0.3230,  0.1686, -0.1294]],
       requires_grad=True)
Parameter containing:
tensor([-0.3254], requires_grad=True)


<ipython-input-5-78fd4d7fbf82>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  load_saved_model = torch.load(file)


***method which is recommended to save and load pytorch models.***

In [6]:
file = 'model.pth_1'
torch.save(model.state_dict(), file)

In [7]:
# In this method we have to define the model again before loading the model
# one more thing using this sate_dict() method we can save any dictonary in this function like we saved the model

loaded_model = LogisticRegression(input_dimension = 6, output_dimension = 1)
loaded_model.load_state_dict(torch.load(file))
loaded_model.eval()

<ipython-input-7-72c21843d2fe>:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load(file))


LogisticRegression(
  (layer): Linear(in_features=6, out_features=1, bias=True)
)

In [8]:
for parametres in loaded_model.parameters():
  print(parametres)

Parameter containing:
tensor([[-0.1257, -0.3965,  0.1026, -0.3230,  0.1686, -0.1294]],
       requires_grad=True)
Parameter containing:
tensor([-0.3254], requires_grad=True)


```
Thik hai dekhte hai
```

In [9]:
# As we know we can save any dictonary in state dict method so if we have an optimizer and learning rate we can save that also.
learning_rate = 0.001
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.001, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}




```
Saving checkpoints using state_dict()
```



In [12]:
checkpoint = {
    'epoch' : 90,
    'model_state' : model.state_dict(),
    'optimizer_state' : optimizer.state_dict()
}
torch.save(checkpoint, 'checkpoint.pth')

In [13]:
loaded_checkpoint = torch.load('checkpoint.pth')
epoch = loaded_checkpoint['epoch']

<ipython-input-13-9de389a9c2cf>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_checkpoint = torch.load('checkpoint.pth')


In [14]:
model = LogisticRegression(input_dimension = 6, output_dimension = 1)
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [16]:
model.load_state_dict(checkpoint['model_state'])
optimizer.load_state_dict(checkpoint['optimizer_state'])

In [17]:
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.001, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}
